version: '3'
services:
  app:
    image: pycon-law-rag-backend:85035d7
    
    container_name: pycon-law-rag-backend
    environment:
      - WORKERS=1
      - GPU_ID=1,2
      
      # - TYPE_HOST=typesense
      # - TYPE_API_KEY=tomandjerry
      # - MEILI_HOST=meilisearch
      # - MEILI_API_KEY=V5ZEsSGoRYeb2GwLMYb8q1XbfRdY7vCaw1DwTB9enWg
    #    volumes:
    #      - /NLP/Z00051780/pretrained:/models
    ports:
      - 15012:15012
    # volumes:
    #   - $PWD:/app
    volumes:
      - $PWD/backend:/app
  ui:
    image: pycon-law-rag-frontend:fc17fe2
    container_name: pycon-law-rag-frontend
    environment:
      - BACKEND_URL = http://pycon-law-rag-backend:15012
    build:
      context: ./frontend/
      dockerfile: ./frontend/docker/Dockerfile
    ports:
      - 15021:8501
    volumes:
      - $PWD/frontend:/app